kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  ## there exists: kindest/node:v1.23.6 and kindest/node:v1.24.1. Tested with 1.23.3
  image: kindest/node:v1.23.6
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
